package git

import (
	"context"
	"fmt"
	"os/exec"
	"strings"
)

// PROptions holds parameters for creating a pull request.
type PROptions struct {
	Owner, Repo  string
	Title, Body  string
	Head, Base   string
	Draft        bool
	Labels       []string
}

// PRResult holds the outcome of a PR creation.
type PRResult struct {
	URL    string
	Number int
	Draft  bool
}

// PRCreator creates and queries pull requests.
type PRCreator interface {
	CreatePR(ctx context.Context, opts PROptions) (PRResult, error)
	ExistingPRURL(ctx context.Context, head string) (string, error)
}

// CommandRunner abstracts os/exec for test injection.
type CommandRunner interface {
	Run(ctx context.Context, name string, args ...string) (string, error)
}

// ExecRunner is the real CommandRunner backed by os/exec.
type ExecRunner struct{}

func (ExecRunner) Run(ctx context.Context, name string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, name, args...)
	out, err := cmd.CombinedOutput()
	return strings.TrimSpace(string(out)), err
}

// GHCLIPRCreator creates PRs via the `gh` CLI tool.
type GHCLIPRCreator struct {
	Runner CommandRunner
}

// NewGHCLIPRCreator returns a GHCLIPRCreator using the real os/exec runner.
func NewGHCLIPRCreator() *GHCLIPRCreator {
	return &GHCLIPRCreator{Runner: ExecRunner{}}
}

func (c *GHCLIPRCreator) CreatePR(ctx context.Context, opts PROptions) (PRResult, error) {
	args := []string{
		"pr", "create",
		"--title", opts.Title,
		"--body", opts.Body,
		"--base", opts.Base,
		"--head", opts.Head,
	}
	if opts.Draft {
		args = append(args, "--draft")
	}
	for _, l := range opts.Labels {
		args = append(args, "--label", l)
	}

	out, err := c.Runner.Run(ctx, "gh", args...)
	if err != nil {
		return PRResult{}, fmt.Errorf("gh pr create: %w\n%s", err, out)
	}
	// gh pr create outputs the PR URL on stdout.
	url := strings.TrimSpace(out)
	return PRResult{URL: url, Draft: opts.Draft}, nil
}

func (c *GHCLIPRCreator) ExistingPRURL(ctx context.Context, head string) (string, error) {
	out, err := c.Runner.Run(ctx, "gh", "pr", "view", head, "--json", "url", "--jq", ".url")
	if err != nil {
		// No existing PR is not an error — return empty string.
		return "", nil
	}
	url := strings.TrimSpace(out)
	return url, nil
}

// BuildPRBody assembles a standard PR description.
func BuildPRBody(agentName, summary string, modifiedFiles []string) string {
	var sb strings.Builder
	if summary != "" {
		sb.WriteString("## Summary\n")
		sb.WriteString(summary)
		sb.WriteString("\n\n")
	}
	if len(modifiedFiles) > 0 {
		sb.WriteString("## Changes\n")
		for _, f := range modifiedFiles {
			sb.WriteString("- " + f + "\n")
		}
		sb.WriteString("\n")
	}
	sb.WriteString("---\n")
	fmt.Fprintf(&sb, "Generated by Polvo agent `%s`\n", agentName)
	return sb.String()
}

// ParseOwnerRepo extracts "owner" and "repo" from a GitHub remote URL.
// Supports SSH (`git@github.com:owner/repo.git`) and HTTPS formats.
// Returns empty strings if parsing fails.
func ParseOwnerRepo(remoteURL string) (owner, repo string) {
	u := strings.TrimSuffix(remoteURL, ".git")

	// SSH: git@github.com:owner/repo
	if strings.HasPrefix(u, "git@") {
		if idx := strings.LastIndex(u, ":"); idx >= 0 {
			u = u[idx+1:]
		}
	}

	// HTTPS: https://github.com/owner/repo
	if strings.Contains(u, "github.com/") {
		if idx := strings.Index(u, "github.com/"); idx >= 0 {
			u = u[idx+len("github.com/"):]
		}
	}

	parts := strings.SplitN(u, "/", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", ""
	}
	return parts[0], parts[1]
}
