// Package report manages analysis reports (laudos).
package report

import (
	"time"

	"github.com/co2-lab/polvo/internal/agent"
)

// Severity levels for report findings.
const (
	SeverityInfo     = "info"
	SeverityWarning  = "warning"
	SeverityHigh     = "high"
	SeverityCritical = "critical"
)

// Report is a structured analysis document generated by agents.
type Report struct {
	ID        string         `json:"id"`
	Agent     string         `json:"agent"`
	Guide     string         `json:"guide"`
	File      string         `json:"file"`
	Timestamp time.Time      `json:"timestamp"`
	Severity  string         `json:"severity"`
	Decision  string         `json:"decision,omitempty"` // APPROVE, REJECT, COHERENT, DIVERGENT
	Summary   string         `json:"summary"`
	Findings  []agent.Finding `json:"findings"`
	Context   ReportContext  `json:"context"`
}

// ReportContext holds additional context for the report.
type ReportContext struct {
	Diff         string   `json:"diff,omitempty"`
	RelatedFiles []string `json:"related_files,omitempty"`
	PRNumber     int      `json:"pr_number,omitempty"`
	PRURL        string   `json:"pr_url,omitempty"`
}

// NewReport creates a new report from an agent result.
func NewReport(agentName, guideName, file string, result *agent.Result) *Report {
	severity := SeverityInfo
	for _, f := range result.Findings {
		switch f.Severity {
		case "critical":
			severity = SeverityCritical
		case "error", "high":
			if severity != SeverityCritical {
				severity = SeverityHigh
			}
		case "warning":
			if severity == SeverityInfo {
				severity = SeverityWarning
			}
		}
	}

	return &Report{
		ID:        generateID(),
		Agent:     agentName,
		Guide:     guideName,
		File:      file,
		Timestamp: time.Now(),
		Severity:  severity,
		Decision:  result.Decision,
		Summary:   result.Summary,
		Findings:  result.Findings,
	}
}

// ToMarkdown renders the report as markdown for PR comments.
func (r *Report) ToMarkdown() string {
	md := "## Polvo Report: " + r.Agent + "\n\n"
	md += "**File:** `" + r.File + "`\n"
	md += "**Decision:** " + r.Decision + "\n"
	md += "**Severity:** " + r.Severity + "\n\n"
	md += "### Summary\n" + r.Summary + "\n\n"

	if len(r.Findings) > 0 {
		md += "### Findings\n\n"
		for _, f := range r.Findings {
			md += "- **" + f.Severity + "** "
			if f.File != "" {
				md += "`" + f.File + "`"
				if f.Line > 0 {
					md += " (line " + itoa(f.Line) + ")"
				}
				md += ": "
			}
			md += f.Message
			if f.Suggestion != "" {
				md += "\n  > Suggestion: " + f.Suggestion
			}
			md += "\n"
		}
	}

	return md
}

func generateID() string {
	return time.Now().Format("20060102-150405") + "-" + randomSuffix()
}

func randomSuffix() string {
	t := time.Now().UnixNano()
	return itoa(int(t % 10000))
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	result := ""
	neg := n < 0
	if neg {
		n = -n
	}
	for n > 0 {
		result = string(rune('0'+n%10)) + result
		n /= 10
	}
	if neg {
		result = "-" + result
	}
	return result
}
