// Package agent implements the agent execution layer.
package agent

import "context"

// Role defines whether an agent authors content or reviews it.
type Role string

const (
	RoleAuthor   Role = "author"
	RoleReviewer Role = "reviewer"
)

// Result is the output of an agent execution.
type Result struct {
	// Decision for reviewers: APPROVE or REJECT
	Decision string
	// Content generated by author agents (file content)
	Content string
	// Summary of what was done
	Summary string
	// Findings for reports
	Findings []Finding
}

// Finding is a single issue found during analysis.
type Finding struct {
	File       string `json:"file"`
	Line       int    `json:"line,omitempty"`
	Severity   string `json:"severity"` // error, warning, info
	Category   string `json:"category"`
	Message    string `json:"message"`
	Suggestion string `json:"suggestion"`
}

// Agent represents an executable agent tied to a guide.
type Agent interface {
	// Name returns the agent/guide name.
	Name() string
	// Role returns author or reviewer.
	Role() Role
	// Execute runs the agent with the given context.
	Execute(ctx context.Context, input *Input) (*Result, error)
}

// Input provides all context an agent needs to execute.
type Input struct {
	File            string
	Content         string
	Diff            string
	Event           string
	ProjectRoot     string
	Interface       string
	Spec            string
	Feature         string
	PRDiff          string
	PRComments      string
	PreviousReports string
	FileHistory     string
}
