import type { Theme } from './types'

export const mintLight: Theme = {
  id: 'mint-light',
  label: 'Mint Light',
  variables: {
    '--surface-void':    '#d8ede4',
    '--surface-base':    '#f0f4f2',
    '--surface-low':     '#e4ede8',
    '--surface-panel':   '#eaf2ee',
    '--surface-raised':  '#dceae2',
    '--surface-overlay': '#d0e4da',
    '--surface-input':   '#e8f0ec',
    '--border':          '#b0ccbc',
    '--border-subtle':   '#c8ddd2',
    '--border-focus':    '#00a876',
    '--mint':            '#00a876',
    '--mint-dim':        '#008f64',
    '--rose':            '#e0426e',
    '--rose-dim':        '#b83358',
    '--text-primary':    '#1a2420',
    '--text-secondary':  '#3a5a4a',
    '--text-muted':      '#6a8a7a',
    '--text-disabled':   '#a0c0b0',
    '--text-inverse':    '#f0f4f2',
    '--text-code':       '#1a3028',
    '--code-bg':         '#e0ede6',
    '--status-success':  '#16a34a',
    '--status-error':    '#dc2626',
    '--status-warning':  '#ca8a04',
    '--status-info':     '#0891b2',
    '--status-user':     '#2563eb',
    // Backward-compat aliases
    '--primary':         '#00a876',
    '--accent':          '#e0426e',
    '--text':            '#1a2420',
    '--muted':           '#6a8a7a',
    '--bg':              '#f0f4f2',
    '--bg-dark':         '#e4ede8',
    '--title-bar':       '#e4ede8',
    '--success':         '#16a34a',
    '--error':           '#dc2626',
    '--user':            '#2563eb',
    '--info':            '#0891b2',
  },
}
