import type { Theme } from './types'

export const mintDark: Theme = {
  id: 'mint-dark',
  label: 'Mint Dark',
  variables: {
    '--surface-void':    '#060908',
    '--surface-base':    '#0d1210',
    '--surface-low':     '#0a0e0c',
    '--surface-panel':   '#101914',
    '--surface-raised':  '#162118',
    '--surface-overlay': '#1a2820',
    '--surface-input':   '#0c1410',
    '--border':          '#1a3a2a',
    '--border-subtle':   '#122218',
    '--border-focus':    '#00ffab',
    '--mint':            '#00ffab',
    '--mint-dim':        '#00c882',
    '--rose':            '#ff5e8e',
    '--rose-dim':        '#cc4a72',
    '--text-primary':    '#e0e0e0',
    '--text-secondary':  '#8aab98',
    '--text-muted':      '#4a6a5a',
    '--text-disabled':   '#2a4a38',
    '--text-inverse':    '#0d1210',
    '--text-code':       '#d4e8da',
    '--code-bg':         '#0f1a14',
    '--status-success':  '#7fd88f',
    '--status-error':    '#e06c75',
    '--status-warning':  '#e8b84b',
    '--status-info':     '#56b6c2',
    '--status-user':     '#5c9cf5',
    // Backward-compat aliases for ThemeThumbnail
    '--primary':         '#00ffab',
    '--accent':          '#ff5e8e',
    '--text':            '#e0e0e0',
    '--muted':           '#4a6a5a',
    '--bg':              '#0d1210',
    '--bg-dark':         '#0a0e0c',
    '--title-bar':       '#0a0e0c',
    '--success':         '#7fd88f',
    '--error':           '#e06c75',
    '--user':            '#5c9cf5',
    '--info':            '#56b6c2',
  },
}
