import type { Theme } from './types'

export const monochrome: Theme = {
  id: 'monochrome',
  label: 'Monochrome',
  variables: {
    '--surface-void':    '#050505',
    '--surface-base':    '#111111',
    '--surface-low':     '#0a0a0a',
    '--surface-panel':   '#161616',
    '--surface-raised':  '#1e1e1e',
    '--surface-overlay': '#252525',
    '--surface-input':   '#0d0d0d',
    '--border':          '#333333',
    '--border-subtle':   '#222222',
    '--border-focus':    '#c0c0c0',
    '--mint':            '#c0c0c0',
    '--mint-dim':        '#a0a0a0',
    '--rose':            '#808080',
    '--rose-dim':        '#606060',
    '--text-primary':    '#e8e8e8',
    '--text-secondary':  '#aaaaaa',
    '--text-muted':      '#666666',
    '--text-disabled':   '#3a3a3a',
    '--text-inverse':    '#111111',
    '--text-code':       '#d8d8d8',
    '--code-bg':         '#0d0d0d',
    '--status-success':  '#66cc66',
    '--status-error':    '#ff6666',
    '--status-warning':  '#ccaa44',
    '--status-info':     '#6699cc',
    '--status-user':     '#aaaaaa',
    // Backward-compat aliases
    '--primary':         '#c0c0c0',
    '--accent':          '#808080',
    '--text':            '#e8e8e8',
    '--muted':           '#666666',
    '--bg':              '#111111',
    '--bg-dark':         '#0a0a0a',
    '--title-bar':       '#0a0a0a',
    '--success':         '#66cc66',
    '--error':           '#ff6666',
    '--user':            '#aaaaaa',
    '--info':            '#6699cc',
  },
}
