import type { Theme } from './types'

export const ocean: Theme = {
  id: 'ocean',
  label: 'Ocean',
  variables: {
    '--surface-void':    '#040810',
    '--surface-base':    '#0d1220',
    '--surface-low':     '#090e1c',
    '--surface-panel':   '#101828',
    '--surface-raised':  '#162030',
    '--surface-overlay': '#1a2840',
    '--surface-input':   '#0a1018',
    '--border':          '#1a3050',
    '--border-subtle':   '#102040',
    '--border-focus':    '#00d4ff',
    '--mint':            '#00d4ff',
    '--mint-dim':        '#00aacf',
    '--rose':            '#ff4081',
    '--rose-dim':        '#cc3368',
    '--text-primary':    '#ddf0fa',
    '--text-secondary':  '#7aaabb',
    '--text-muted':      '#3a5a6a',
    '--text-disabled':   '#1a3040',
    '--text-inverse':    '#0d1220',
    '--text-code':       '#c0e8f8',
    '--code-bg':         '#081020',
    '--status-success':  '#69f0ae',
    '--status-error':    '#ff5252',
    '--status-warning':  '#ffca28',
    '--status-info':     '#40c4ff',
    '--status-user':     '#40c4ff',
    // Backward-compat aliases
    '--primary':         '#00d4ff',
    '--accent':          '#ff4081',
    '--text':            '#ddf0fa',
    '--muted':           '#3a5a6a',
    '--bg':              '#0d1220',
    '--bg-dark':         '#090e1c',
    '--title-bar':       '#090e1c',
    '--success':         '#69f0ae',
    '--error':           '#ff5252',
    '--user':            '#40c4ff',
    '--info':            '#40c4ff',
  },
}
