import type { Theme } from './types'

export const sunset: Theme = {
  id: 'sunset',
  label: 'Sunset',
  variables: {
    '--surface-void':    '#080408',
    '--surface-base':    '#130d12',
    '--surface-low':     '#0e0a0d',
    '--surface-panel':   '#18101a',
    '--surface-raised':  '#201520',
    '--surface-overlay': '#281a2a',
    '--surface-input':   '#100c10',
    '--border':          '#3d1a2a',
    '--border-subtle':   '#260e18',
    '--border-focus':    '#ff9f4a',
    '--mint':            '#ff9f4a',
    '--mint-dim':        '#e08030',
    '--rose':            '#ffd700',
    '--rose-dim':        '#ccac00',
    '--text-primary':    '#f0e0d0',
    '--text-secondary':  '#b08070',
    '--text-muted':      '#6b4226',
    '--text-disabled':   '#3d2018',
    '--text-inverse':    '#130d12',
    '--text-code':       '#e8c8a0',
    '--code-bg':         '#100808',
    '--status-success':  '#7bed9f',
    '--status-error':    '#ff6b81',
    '--status-warning':  '#ffd32a',
    '--status-info':     '#70a1ff',
    '--status-user':     '#70a1ff',
    // Backward-compat aliases
    '--primary':         '#ff9f4a',
    '--accent':          '#ffd700',
    '--text':            '#f0e0d0',
    '--muted':           '#6b4226',
    '--bg':              '#130d12',
    '--bg-dark':         '#0e0a0d',
    '--title-bar':       '#0e0a0d',
    '--success':         '#7bed9f',
    '--error':           '#ff6b81',
    '--user':            '#70a1ff',
    '--info':            '#70a1ff',
  },
}
