import type { Theme } from './types'

export const warpBW: Theme = {
  id: 'warp-bw',
  label: 'Warp B&W',
  variables: {
    '--surface-void':    '#000000',
    '--surface-base':    '#0a0a0a',
    '--surface-low':     '#050505',
    '--surface-panel':   '#121212',
    '--surface-raised':  '#1a1a1a',
    '--surface-overlay': '#1f1f1f',
    '--surface-input':   '#0f0f0f',
    '--border':          '#2a2a2a',
    '--border-subtle':   '#1a1a1a',
    '--border-focus':    '#ffffff',
    '--mint':            '#ffffff',
    '--mint-dim':        '#a1a1aa',
    '--rose':            '#e4e4e7',
    '--rose-dim':        '#71717a',
    '--text-primary':    '#ffffff',
    '--text-secondary':  '#a1a1aa',
    '--text-muted':      '#71717a',
    '--text-disabled':   '#3f3f46',
    '--text-inverse':    '#000000',
    '--text-code':       '#f4f4f5',
    '--code-bg':         '#0f0f0f',
    '--status-success':  '#ffffff',
    '--status-error':    '#e4e4e7',
    '--status-warning':  '#a1a1aa',
    '--status-info':     '#e4e4e7',
    '--status-user':     '#a1a1aa',
    // Backward-compat aliases
    '--primary':         '#ffffff',
    '--accent':          '#e4e4e7',
    '--text':            '#ffffff',
    '--muted':           '#71717a',
    '--bg':              '#0a0a0a',
    '--bg-dark':         '#000000',
    '--title-bar':       '#000000',
    '--success':         '#ffffff',
    '--error':           '#e4e4e7',
    '--user':            '#a1a1aa',
    '--info':            '#e4e4e7',
  },
}
